project:
  type: book
  output-dir: docs

book:
  title: "Geographic Data Science in R and Python"
  author: "Dr. Elisabetta Pietrostefani & Dr. Carmen Cabrera-Arnau"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - syllabus.qmd
    - overview.qmd
    - assess.qmd
    - part: environ.qmd
      chapters:
        - environR.qmd
        - environPy.qmd
    - part: openscience.qmd
      chapters:
        - concepts_openscience.qmd
        - openscienceR.qmd
        - opensciencePython.qmd
    - part: spatialdata.qmd
      chapters:
        - concepts_spatialdata.qmd
        - spatialdataR.qmd
        - spatialdataPy.qmd
    - part: mapvector.qmd
      chapters:
        - concepts_mapvector.qmd
        - mapvectorR.qmd
        - mapvectorPy.qmd
    - part: mapraster.qmd
      chapters:
        - concepts_mapraster.qmd
        - maprasterR.qmd
        - maprasterPy.qmd
    - references.qmd

  page-footer:
    left: |
      Geographic Data Science in R and Python by Elisabetta Pietrostefani and Carmen Cabrera-Arnau.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url:  https://pietrostefani.github.io/wma
  repo-url: https://github.com/pietrostefani/gds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  twitter-card:
    creator: "@EPietrostefani"

bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    - r4gds.scss
  pdf:
    documentclass: scrreprt

editor: visual

