# Assessments {.unnumbered}

## Assignment I

-   **Title:** Programmed Map
-   **Type:** Coursework
-   Due date: 4th November 2024 (week 7)
-   40% of the final mark
-   Chance to be reassessed
-   Electronic submission only

This assignment will be evaluated on technical data processing, map design abilities (assemblage), and design overall narrative.

Once you have created your map, you will need to present it. Write up to 500 about the choices you made to create the map.

-  **[Full Assignment details](https://theuniversityofliverpool-my.sharepoint.com/:b:/g/personal/pietrost_liverpool_ac_uk/EVtY1PO8LRJCncXtmiq4lAMBC6in9db94tZ0Cepzheoepg?e=UtyoVC)**

You will submit an `.html` file obtained by rendering your `.qmd` in `R` or `.ipynb` Jupyter Notebook in `Python`.

- If you are doing the assignment in `R`: You can start from this **[.qmd file](https://theuniversityofliverpool-my.sharepoint.com/:u:/g/personal/pietrost_liverpool_ac_uk/EfRYCY5AuLNEsmEtT5lBbKgBF2Q5gTcYvRia13gLdzlNLA?e=fNzdf3)** to render the `html`. Other file formats will not be accepted.

- If you are doing the assignment in `Python`: To do so, in your `.ipynb` file, follow these steps: `File –> Save and Export as.. –> HTML`. Prior to this step, the notebook needs to be rendered (i.e. all the cells should be executed).  Other file formats will not be accepted.

### Submit

Once completed, you will need to submit the following:

**An html version of an .qmd document with R integrated code.**

The assignment will be evaluated based on three main pillars, on which you will have to be successful to achieve a good mark:

1.  **Data Processing:** Your proficiency in handling and manipulating data will be a fundamental aspect of the assessment.

2.  **Map assemblage** This includes your ability to master technologies that allow you to create a compelling map.

3.  **Design and narrative:** Your success in designing an appealing map with a compelling narrative will play a pivotal role in your overall evaluation.

## Assignment II

-   **Title:** Computational Essay
-   **Type:** Coursework
-   Due date: 5th December 2024 (week 11)
-   60% of the final mark
-   Chance to be reassessed
-   Electronic submission only

A 4,000 word computational essay on a geographic data set which they have explored and analysed using the skills and techniques developed during the course. Students will complete an essay which combines both code, data visualisation and prose supported by references in order to demonstrate sound understanding of all learning outcomes.

- **[Full Assignment details]()**

- **[Data in csv format if you are not using API]()**

**Overview**

Here’s the premise. You will take the role of a real-world geographic data scientist tasked to explore datasets on Los Angeles and find useful insights for a variety of city decision-makers. It does not matter if you have never been to the Los Angeles. In fact, this will help you focus on what you can learn about the city through the data, without the influence of prior knowledge. Furthermore, the assessment will not be marked based on how much you know about Los Angeles but instead about how much you can show you have learned through analysing data. You will need contextualise your project by highlighting the opportunities and limitations of ‘old’ and ‘new’ forms of spatial data and reference relevant literature.

**What is a Computational Essay?**

A computational essay is an essay whose narrative is supported by code and computational results that are included in the essay itself. This piece of assessment is equivalent to 4,000 word. However, this is the overall weight. Since you will need to create not only narrative but also code and figures, here are the requirements:

-   Maximum of 1,000 words (ordinary text) (references do not contribute to the word count). You should answer the specified questions within the narrative. The questions should be included within a wider analysis.

-   Up to four maps or figures (a figure may include more than one map and will only count as one but needs to be integrated in the same overall output)

-   Up to one table

**There are three kinds of elements in a computational essay:**

1.  Ordinary text (in English)

2.  Computer input (R or Python)

3.  Computer output

These three elements all work together to express what's being communicated.

## Marking Criteria

This course follows the standard marking criteria (the general ones and those relating to GIS assignments in particular) set by the School of Environmental Sciences. Please make sure to check the student handbook and familiarise with them. In addition to these generic criteria, the following specific criteria will be used in cases where computer code is part of the work being assessed:

-   0-15: the code does not run and there is no documentation to follow it.
-   16-39: the code does not run, or runs but it does not produce the expected outcome. There is some documentation explaining its logic.
-   40-49: the code runs and produces the expected output. There is some documentation explaining its logic.
-   50-59: the code runs and produces the expected output. There is extensive documentation explaining its logic.
-   60-69: the code runs and produces the expected output. There is extensive documentation, properly formatted, explaining its logic.
-   70-79: all as above, plus the code design includes clear evidence of skills presented in advanced sections of the course (e.g. custom methods, list comprehensions, etc.).
-   80-100: all as above, plus the code contains novel contributions that extend/improve the functionality the student was provided with (e.g. algorithm optimizations, novel methods to perform the task, etc.).

## Generative Artificial Intelligence 

•	You are reminded that the inappropriate use of Generative Artificial Intelligence Tools in the preparation of assignments is strictly prohibited.

•	Assignments should be prepared using your own words.  All use of AI translation tools should be properly acknowledged.   Extensive use of AI proof-reading tools is prohibited.  Whilst you may use spelling/grammar checks typically found in word-processing packages, using AI tools to change words/sentence structure may incur an Academic Integrity penalty.

•	If your assessment is referred for an Academic Integrity Investigation, you may be asked to demonstrate that the work you have submitted is your own.  Therefore, it is advised that you keep hold of earlier files, drafts, notes and other relevant preparatory materials that you have used.

