# R {.unnumbered}

To run the analysis and reproduce the code in R, you need the following software:

-   R-4.2.2
-   RStudio 2022.12.0-353
-   The list of libraries in the next section

To install and update:

-   R, download the appropriate version from [The Comprehensive R Archive Network (CRAN)](https://cran.r-project.org)
-   RStudio, download the appropriate version from [Posit](https://posit.co/download/rstudio-desktop/)

To check your version of:

-   R and libraries run `sessionInfo()`
-   RStudio click `help` on the menu bar and then `About`
-   Quarto check the `version` file in the quarto folder on your computer.

## R List of libraries

The list of libraries used in this book is provided below:

-   `sf`
-   `geojsonsf`
-   `mapview`

# Resources

Some help along the way with:

1. [R for Data Science](https://r4ds.had.co.nz/). R4DS teaches you how to do data science with R: You’ll learn how to get your data into R, get it into the most useful structure, transform it, visualise it and model it.

2. [Spatial Data Science](https://r-spatial.org/book/) by Edzer Pebesma and Roger Bivand introduces and explains the concepts underlying spatial data.

3. [Geo-computation with R](https://r.geocompx.org/) by Robin Lovelace, Jakub Nowosad and Jannes Muenchow.
