# Do-It-Yourself {#sec-map-raster-DIY .unnumbered}

Let's work with some more raster data! In this section, you will practice the concepts and code we have learnt in this block. Happy hacking!

## Data preparation

We are going to work with some data of Corsica, a region of France. If you want to challenge yourself you can download the data and pre-process it yourself using [Earth Explorer](https://earthexplorer.usgs.gov/).

If not you can download it [here](https://theuniversityofliverpool-my.sharepoint.com/:u:/g/personal/pietrost_liverpool_ac_uk/EYaxWikecFxPqLTzUNp7Ch0Bxxiv9hyv1bg5lzh6fUcTrg?e=bTdi70). You will need to be signed into your UoL account.

You will then need to download the shapefiles for France. You can use [GADM](https://gadm.org/formats.html) which has made available national and subnational shapefiles for the world.

### Task I: Join by attribute

1.  Plot your data and the CRS. Make sure your files are in the same CRS. Usually France uses the projected coordinate system [Lambert 93](https://epsg.io/2154) or EPSG = 2154
2.  Crop and Mask the data
3.  Visualise the elevation using `tmap`
4.  use `geom_spatraster_contour_filled` to create a contour map with specific breaks

## Advanced

Working on a time-series representation of the evolution of Nights Lights in a **country of your choice**. As in the lab, the data can be found [here](https://www.ngdc.noaa.gov/eog/data/web_data/v4composites/).

### Task II:

1.  Process the data and make a map with at least two years of night lights data.
2.  Think about the story the data is telling you.
    -   How have night lights evolved over time in your country of choice? Remember this will mean different things for different countries.

    -   What choices have you made in terms of bins, colours, zoom level to tell your story?

<iframe src="https://ourworldindata.org/grapher/share-of-the-population-with-access-to-electricity" loading="lazy" style="width: 100%; height: 600px; border: 0px none;"></iframe>
