# Overview {.unnumbered}

## Aims

This module aims to:



## Learning Outcomes

By the end of the module, students should be able to:

**For All** 

(1) Demonstrate advanced GIS/GDS concepts and be able to use the tools programmatically to import, manipulate and analyse data in different formats.

(2) Understand the motivation and inner workings of the main methodological approaches of GDS, both analytical and visual.

(3) Evaluate the suitability of a specific technique, what it can offer and how it can help answer questions of interest.

(4) Apply a number of spatial analysis techniques and how to interpret the results, in the process of turning data into information.

(5) When faced with a new data-set, work independently using GIS/GDS tools programmatically.

**Only for MSc-level students**
(6) Demonstrate a sound understanding of how real-world (geo)data are produced, their potential insights and biases, as well as opportunities and limitations.

## Feedback

FILL IN

## Computational Environment

ADD SOMETHING ABOUR R or Python

EDIT the below

This course can be followed by anyone with access to a bit of technical infrastructure. This section details the set of local and online requirements you will need to be able to follow along, as well as instructions or pointers to get set up on your own. This is a centralized section that lists *everything* you will require, but keep in mind that different blocks do not always require everything all the time.

To reproduce the code in the book, you need the most recent version of R and packages. These can be installed following the instructions provided in our [R installation guide](https://gdsl-ul.github.io/r_install/).

### Software

EDIT 

To run the analysis and reproduce the code, you need the following software:

-   QGIS- the stable version (3.22 LTR at the time of writing) is OK, any more recent version will also work.
-   R-4.2.2
-   RStudio 2022.12.0-353
-   Quarto 1.2.280
-   the list of libraries in the next section

To install and update:

-   QGIS, download the appropriate version from [QGIS.org](https://www.qgis.org/en/site/forusers/download.html)
-   R, download the appropriate version from [The Comprehensive R Archive Network (CRAN)](https://cran.r-project.org)
-   RStudio, download the appropriate version from [Posit](https://posit.co/download/rstudio-desktop/)
-   Quarto, download the appropriate version from [the Quarto website](https://quarto.org/docs/get-started/)

To check your version of:

-   R and libraries run `sessionInfo()`
-   RStudio click `help` on the menu bar and then `About`
-   Quarto check the `version` file in the quarto folder on your computer.

### R List of libraries

The list of libraries used in this book is provided below:

### Python set-up

### Online accounts

