# Syllabus {.unnumbered}

## Part 1

**Week 1 -** Introduction and Open Science

**Week 2 -** Spatial Data

**Week 3 -** Mapping Vector Data

**Week 4** - Mapping Raster Data

**Week 5** - Points

**Week 6** - No Lecture & Clinic

`Assignment I`: Programmed Map

## Part 2

**Week 7 -** Spatial Weights

**Week 8** - ESDA

**Week 9** - Clustering

**Week 10** - Spatial Network Analysis

**Week 11** - No lecture & Clinic

`Assignment II`: A computational essay

## Learning Outcomes

- **LO1**	Demonstrate advanced GIS/GDS concepts and be able to use the tools programmatically to import, manipulate and analyse data in different formats.	
- **LO2**	Understand the motivation and inner workings of the main methodological approaches of GDS, both analytical and visual.	
- **LO3**	Evaluate the suitability of a specific technique, what it can offer and how it can help answer questions of interest.	
- **LO4**	Apply a number of spatial analysis techniques and how to interpret the results, in the process of turning data into information.	
- **LO5**	When faced with a new data-set, work independently using GIS/GDS tools programmatically.
-	**LO6**	Demonstrate a sound understanding of how real-world (geo)data are produced, their potential insights and biases, as well as opportunities and limitations.
